# 注意
# 文字列はダブルクオーテーションで囲ってください
# sample = "サンプル"

# Chromiumのパス(特殊な状況のときに # を外して使用)
# browserPath = "/usr/bin/chromium-browser"

# 岩手県入札情報公開サービストップページ
topPage = "https://www.epi-cloud.fwd.ne.jp/koukai/do/KF001ShowAction?name1=0620060006600600"

# この業務名を含むものに絞る
projectTitle = "設計"

# ダウンロードする案件をNew(1週間以内)がついたものに限る (true or false)
downloadOnlyNew = true

# 1ページあたりの表示件数 (10, 25, 50, 100)
numberOfItems = 100

# このキーワードを含むPDFをダウンロードする
pdfKeywords = [
  "公告",
  "位置図",
  "図面",
  "参考資料",
  "平面図"
]

# ファイルチェックを行う(true or false)
fileCheckEnabled = false

# ダウンロードされないファイルがある場合の調整項目
downloadTimeoutSec = 30                   # 案件ごとのダウンロードタイムアウト時間(秒)
pdfClickDelaySec = 3                      # PDFリンクのクリックのスリープ時間 (秒)

# 通知機能設定（Google Apps Scriptへの送信）
[notification]
enabled = false                         # 通知機能を有効にする (true or false)
gasUrl = "https://script.google.com/macros/s/your-gas-deployment-id/exec" # Google Apps ScriptのWebアプリURL
apiKey = "your-api-key"                 # APIキー（認証用）

# Google Drive設定
[googleDrive]
uploadEnabled = false                 # Google Driveへのアップロードを有効にする (true or false)
serviceAccountKeyPath = "./credentials.json" # サービスアカウントのキーファイルのパス（JSONファイル）
folderId = ""                         # アップロード先のフォルダID
spreadsheetId = ""                    # スプレッドシートID

# debug用
[debug]
debugEnabled = false                  # debugモードを有効にする (true or false)
headless = true                       # headlessモードを有効にする (true or false)

# データクリーンアップ設定
[dataCleanup]
enabled = true                        # 古いデータの自動削除を有効にする (true or false)
retentionDays = 3                     # データを保持する日数 (デフォルト: 3)